version: "3"

services:
  mysql:
    build: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=ccj
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ccj
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_unicode_ci
    restart: always
  app:
    build: ./api
    ports:
      - "4400:4400"
    volumes:
      - ./api:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=ccj
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ccj
    depends_on:
      - mysql
    restart: always
volumes:
  mysql-data:
    driver: local
